
export enum FieldType {

	FIELD_TYPE_TEXT = "FIELD_TYPE_TEXT",
	FIELD_TYPE_IMAGE =
	'FIELD_TYPE_IMAGE',
	FIELD_TYPE_CURRENCY =
	'FIELD_TYPE_CURRENCY',
	FIELD_TYPE_NUMBER =
	'FIELD_TYPE_NUMBER',
	FIELD_TYPE_HIDDEN =
	'FIELD_TYPE_HIDDEN',
	FIELD_TYPE_COLOR =
	'FIELD_TYPE_COLOR',
	FIELD_TYPE_CHECKBOX =
	'FIELD_TYPE_CHECKBOX',
	FIELD_TYPE_FIXED_LIST =
	'FIELD_TYPE_FIXED_LIST',
	FIELD_TYPE_DYNAMIC_LIST =
	'FIELD_TYPE_DYNAMIC_LIST',
	FIELD_TYPE_TEXTAREA =
	'FIELD_TYPE_TEXTAREA',
	FIELD_TYPE_PLAIN_LIST =
	'FIELD_TYPE_PLAIN_LIST',
	FIELD_TYPE_DATE =
	'FIELD_TYPE_DATE',
	FIELD_TYPE_TEXTEDITOR = 
	'FIELD_TYPE_TEXTEDITOR',
	FIELD_TYPE_DATETIME=
	'FIELD_TYPE_DATETIME',
	FIELD_TYPE_DOCUMENT=
	'FIELD_TYPE_DOCUMENT',
}

